# Generated by Django 6.1.1 on 2026-10-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='start_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
