# Generated by Django 6.1.1 on 2026-10-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_maintenanceplan_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
